name: "Terraform"

# Defines when the workflow will run
on:
  # Manual trigger using GitHub Actions UI
  workflow_dispatch:
    inputs:
      target:
        description: "Whose account to deploy to"
        required: true
        type: choice
        options:
          - aygbutlowercase
          - danny
          - jasonchilowercase
          - Varun
      # Input parameter to choose between apply or destroy actions
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_apply
        - Terraform_destroy

jobs:
  # Job for applying Terraform configurations
  terraform_apply:
    name: "Terraform_apply"
    # Condition to run this job only when 'Terraform_apply' is selected
    if: ${{ github.event.inputs.action == 'Terraform_apply' }}
    # Specifies the type of runner to use
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target }}

    env:
      # Using GitHub secrets for sensitive values
      TF_VAR_aws_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME}}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      ENVIRONMENT_NAME: ${{ github.event.inputs.target }}

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials for authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Using GitHub secrets for secure credential storage
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Secret variable
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Secret variable
          aws-region: ${{ vars.AWS_REGION }}  # Reference the repository variable
        
      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.1.9 # Specifies Terraform version to use
          terraform_wrapper: false

      # Step 4: Set up Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # Step 5: Initialize Terraform working directory
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 6: Preview the infrastructure changes
      - name: Terraform Plan
        run: terraform plan -var="environment=${{ env.ENVIRONMENT_NAME }}"
        working-directory: ./terraform

      # Step 7: Apply the infrastructure changes
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=${{ env.ENVIRONMENT_NAME }}" # Auto-approve flag skips manual confirmation
        working-directory: ./terraform

      # Step 8: Store Terraform state in S3
      - name: Store state 
        run: aws s3 cp terraform.tfstate s3://stock-news-analyzer-terraform-state-bucket-${{ env.ENVIRONMENT_NAME }}
        working-directory: ./terraform

      # Step 9: Install npm
      - name: Install npm
        run: npm install
        working-directory: ./stock-news-app

      # Step 10: Build React app
      - name: Build React App
        run: npm run build
        working-directory: ./stock-news-app

      # Step 11: Copy React build files to S3
      - name: Upload React App to S3
        run: aws s3 cp . s3://stock-news-analyzer-react-app-bucket-${{ env.ENVIRONMENT_NAME }} --recursive
        working-directory: ./stock-news-app/build

  terraform_destroy:
    name: "Terraform_destroy"
    # Condition to run this job only when 'Terraform_destroy' is selected
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    # Specifies the type of runner to use
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target }}

    env:
      # Using GitHub secrets for sensitive values
      TF_VAR_aws_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME}}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      ENVIRONMENT_NAME: ${{ github.event.inputs.target }}

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials for authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Using GitHub secrets for secure credential storage
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Secret variable
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Secret variable
          aws-region: ${{ vars.AWS_REGION }}  # Reference the repository variable

      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.1.9 # Specifies Terraform version to use
          terraform_wrapper: false

      # Step 4: Retrieve Terraform state from S3
      - name: Retrieve state
        run: aws s3 cp s3://stock-news-analyzer-terraform-state-bucket-${{ env.ENVIRONMENT_NAME }}/terraform.tfstate .
        working-directory: ./terraform

      # Step 5: Initialize terraform working directory
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 6: Destroy the infrastructure
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="environment=${{ env.ENVIRONMENT_NAME }}" # Auto-approve flag skips manual confirmation    
        working-directory: ./terraform